language: python
python:
  - "2.7"
  - "3.6"
env:
  - NSQ_VERSION=0.2.26
# Get some pre-requisites
before_install: "bash scripts/travis/before-install.sh"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: make test
